### PR TITLE
feat: conditional file and directory creation support

### LINKED ISSUE #113: feat: Conditionally create folders
**Description**

Add possibility to conditionally create folders, similarly how mason generates code conditionally

### PR DESCRIPTION
**Pull request by felangel**
## Status

**READY**

## Description

- feat: conditional file and directory creation support (closes #113)

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by lukepighetti** [comment]
Is the use of this feature documented somewhere?

**Comment by felangel** [comment]
> Is the use of this feature documented somewhere?

I need to improve the docs but you can see an example of it in action in the [plugin brick](https://github.com/felangel/mason/tree/master/bricks/plugin)

**Comment by MaximeEglem** [comment]
If you create a filename containing a slash with Mac software, then look at it with terminal, you will see the filename with a colon that will failed for finding the final separator

**Comment by icodeyou** [comment]
Thank you, this is a great feature.
Could you add some documentation for this ?

**Pull request merged**
