### PR TITLE
feat!: computed vars support (new HookContext)

### PR DESCRIPTION
**Pull request by felangel**
## Status

**READY**

## Description

- feat: computed vars support

### Demo

https://user-images.githubusercontent.com/8855632/150920336-35bf54a2-ba1f-46fc-a938-69472f6b5bd5.mp4

### Summary

Mason supports custom script execution via `hooks`. The supported hooks are:

- `pre_gen` - executed immediately before the generation step
- `post_gen` - executed immediately after the generation step

Hooks must be defined in the `hooks` directory at the root of the brick:

```
├── __brick__
├── brick.yaml
└── hooks
    ├── post_gen.dart
    ├── pre_gen.dart
    └── pubspec.yaml
```

❗ Currently mason only supports hooks written in [Dart](https://dart.dev).

##### Hooks Usage

Every hook must contain a `run` method which accepts a `HookContext` from `package:mason/mason.dart`.

For example, given the following `example` brick:

```sh
.
├── __brick__
│   └── example.md
├── brick.yaml
└── hooks
    ├── post_gen.dart
    └── pubspec.yaml
```

where `brick.yaml` looks like:

```yaml
name: example
description: An example brick.
version: 0.1.0+1
vars:
  name:
    type: string
    description: Your name
    default: Dash
    prompt: What is your name?
```

and `pubspec.yaml` looks like:

```yaml
name: example_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mason: any
```

And `post_gen.dart` contains:

```dart
import 'package:mason/mason.dart';

void run(HookContext context) {
  context.logger.info('hello {{name}}!');
}
```

The result of running `mason make example --name Dash` would be:

```sh
mason make example --name Dash
✓ Made brick example (0.0s)
✓ Generated 1 file:
  /Users/dash/mason/example/example.md (new)
hello Dash!
```

`HookContext` can be used to access/modify the brick `vars` or to interface with the `MasonLogger` instance.

```dart
import 'package:mason/mason.dart';

void run(HookContext context) {
  // Read/Write vars
  context.vars = {...context.vars, 'custom_var': 'foo'};
  
  // Use the logger
  context.logger.info('hello from pre_gen.dart');
}
```

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [X] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by mtwichel** [comment]
Hey @felangel , it looks super amazing and I can't wait to use it. I tried it out and have a few qs:

1. Should it support having multiple dart files and importing those into your hooks, ie:

```dart
import './computation.dart';

Future<void> run(HookContext context) async {
  final result = computation();
  context.vars = result;
}
```

I tried this with a real-world example (my github actions generator), and a simple example like this one. The real world stalled out and wouldn't finish running, the simple one through an error saying the function wasn't found. I don't believe importing like that is supported, but I just wanted to double-check this was intended. (although I suppose you can add it to your own package and import that :rocket:)

2. I then refactored my github actions generator into a single file, and here it is: https://gist.github.com/mtwichel/e0db20f0340dd316a5991a39661526fa. Every time  I run it (on a real-world project or not), it throws an error with this message:
`../../runtime/vm/message_snapshot.cc: 551: error: expected: !lib.IsNull()`

<details> <summary>Full Stacktrace</summary>

```stacktrace
../../runtime/vm/message_snapshot.cc: 551: error: expected: !lib.IsNull()
version=2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"
pid=27005, thread=9223, isolate_group=main(0x7fd269822400), isolate=main(0x7fd26980e800)
isolate_instructions=10760ece0, vm_instructions=10760ece0
  pc 0x000000010786d3f4 fp 0x000070000bf2fa30 dart::Profiler::DumpStackTrace(void*)+0x64
  pc 0x000000010760eeb4 fp 0x000070000bf2fb10 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x00000001077d60ca fp 0x000070000bf2fb70 dart::ReadApiMessage(dart::Zone*, dart::Message*)+0x896a
  pc 0x00000001077cc744 fp 0x000070000bf2fbd0 dart::MessageDeserializer::Deserialize()+0x244
  pc 0x00000001077cd728 fp 0x000070000bf2fd00 dart::ReadMessage(dart::Thread*, dart::Message*)+0xf8
  pc 0x000000010779e17c fp 0x000070000bf2fde0 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0xac
  pc 0x00000001077c815c fp 0x000070000bf2fe50 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x12c
  pc 0x00000001077c886f fp 0x000070000bf2fea0 dart::MessageHandler::TaskCallback()+0x1df
  pc 0x00000001078f46d8 fp 0x000070000bf2ff30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x138
  pc 0x00000001078f4b6d fp 0x000070000bf2ff60 dart::ThreadPool::Worker::Main(unsigned long)+0x5d
  pc 0x0000000107867bdf fp 0x000070000bf2ffb0 dart::OSThread::GetMaxStackSize()+0xaf
  pc 0x00007ff8169044f4 fp 0x000070000bf2ffd0 _pthread_start+0x7d
  pc 0x00007ff81690000f fp 0x000070000bf2fff0 thread_start+0xf
-- End of DumpStackTrace
```
</details>

I'm not sure if I'm doing something wrong, or it's a legit bug. I tried to minimally reproduce and couldn't, and I also did my best to debug but I'm still not the best isolates expert :/ But I thought I'd share it along and see if it's an issue.

Other than that, the hooks look great so far! Very exciting 💙

**Comment by mtwichel** [comment]
> Every time I run it (on a real-world project or not), it throws an error with this message:

I forgot to mention, due to my primo logger.info debuging 😎, I think the `run` function is terminating as it's logging everything the logger should. It looks like the error occurs after terminating the function.

**Comment by felangel** [comment]
> Hey @felangel , it looks super amazing and I can't wait to use it. I tried it out and have a few qs:
> 
> 1. Should it support having multiple dart files and importing those into your hooks, ie:
> 
> ```dart
> import './computation.dart';
> 
> Future<void> run(HookContext context) async {
>   final result = computation();
>   context.vars = result;
> }
> ```
> 
> I tried this with a real-world example (my github actions generator), and a simple example like this one. The real world stalled out and wouldn't finish running, the simple one through an error saying the function wasn't found. I don't believe importing like that is supported, but I just wanted to double-check this was intended. (although I suppose you can add it to your own package and import that 🚀)
> 
> 2. I then refactored my github actions generator into a single file, and here it is: https://gist.github.com/mtwichel/e0db20f0340dd316a5991a39661526fa. Every time  I run it (on a real-world project or not), it throws an error with this message:
>    `../../runtime/vm/message_snapshot.cc: 551: error: expected: !lib.IsNull()`
> 
> Full Stacktrace
> I'm not sure if I'm doing something wrong, or it's a legit bug. I tried to minimally reproduce and couldn't, and I also did my best to debug but I'm still not the best isolates expert :/ But I thought I'd share it along and see if it's an issue.
> 
> Other than that, the hooks look great so far! Very exciting 💙

Hey @mtwichel 👋 

Thanks for the feedback!

This is working as expected. For the sake of simplicity, the only files supported in `hooks` are `pre_gen.dart`, `post_gen.dart`, and a `pubspec.yaml`. If we want to support any arbitrary code being imported then it will increase the complexity because in theory a hook can import a file that lives outside of the brick:

```dart
import '../../../some/dart/file.dart';

void run(HookContext context) {...}
```

Even though the above is technically valid, in order to support this we'd need to trace all the imports and copy the relevant code as part of the brick bundle. Unless there's a really compelling use case I would prefer to limit the scope of hooks to just a single dart file per hook. In terms of code reuse, hooks can reference other packages so you can always import an external dependency from either pub or git and reference it in the corresponding hook:

```dart
import 'package:my_custom_hook/my_custom_hook.dart';

void run(HookContext context) {...}
```

Let me know what you think and thanks again for the feedback! 🙏

**Comment by mtwichel** [comment]
@felangel I personally think it's totally reasonable to only allow `pre_gen.dart` and `post_gen.dart`. Honestly, if you need way more complex code, probably best to wrap it in a package anyway. I think we're all good :)

**Pull request merged**
