### PR TITLE
feat: implement error conflict strategy

### PR DESCRIPTION
**Pull request by mtwichel**
## Status

**READY**

## Description

This PR adds a new option to the `--on-conflict` flag on the `mason make` command: `error`.

This option will generate files just like `overwrite`; however, if any of the files have changed, it will end by throwing a `MasonException` (which will cause it to end with an error exit code).

This is super useful for running in continuous integration so you can catch when someone forgets to run mason make before submitting.

```yaml
name: Verify mason was ran

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify mason make
         run: dart run mason make my_brick --on-conflict error
```

A few choices I made in implementing:
- The logger will tell you which files have conflicts and which are identical
- The CLI will not immediately stop when it finds a conflict. Instead, it will try to generate all files and log which ones are conflicting. That way, you'll have the output of all the files that were bad.

I wasn't sure how to deal with the pub score verifier error, but I'm happy to fix it if you give me some direction :)

Thanks 💙 

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
Thanks so much for taking the time to open this PR! 🙏 

I thought about it a bit more and I wonder what your thoughts are on using `--set-exit-if-changed` instead similar to how `dart format` works.

If we used `--set-exit-if-changed` the change can scoped to just `mason_cli` and the surface area is a lot smaller (see #224 for a draft PR).

Let me know what you think and thanks again!

**Comment by mtwichel** [comment]
Thanks @felangel 
> If we used --set-exit-if-changed the change can scope to just mason_cli and the surface area is a lot smaller

Yeah, I think that makes sense. It does add another flag, but since it's pretty common I don't think that's an issue at all. Thanks!

**Comment by felangel** [comment]
> Thanks @felangel
> 
> > If we used --set-exit-if-changed the change can scope to just mason_cli and the surface area is a lot smaller
> 
> Yeah, I think that makes sense. It does add another flag, but since it's pretty common I don't think that's an issue at all. Thanks!

I'm still going back and forth on it...need to think about it a bit more 🤔

**Comment by felangel** [comment]
This should be available now via #224 🎉

**Pull request closed without merging**
