### PR TITLE
refactor: use `super.key`

### PR DESCRIPTION
**Pull request by tenhobi**
## Status

**READY**

## Description

Removed the super constructor and use `super.key` instead. At your command, sir. 🙌 👑 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by wolfenrain — APPROVED** [review]

**Comment by tenhobi** [comment]
Hmm, I don't really see what the issue is with those builds. 🤔

**Comment by felangel** [comment]
> Hmm, I don't really see what the issue is with those builds. 🤔

Thanks for the contribution! I'll take a look at the builds and get this merged first thing tomorrow 👍 🙏

**Review by renancaraujo — APPROVED** [review]

**Comment by tenhobi** [comment]
Hey @felangel, did you manage to figure it out? I tried to clone the repo and make tests run locally but received timeouts a lot; so no luck from my side. 🥲

**Comment by felangel** [comment]
> Hey @felangel, did you manage to figure it out? I tried to clone the repo and make tests run locally but received timeouts a lot; so no luck from my side. 🥲

I’m planning to get all PRs merged today sorry for the delay but don’t worry about it 👍

**Review by felangel — APPROVED** [review]

**Pull request merged**
