### PR TITLE
feat(mason): define `BrickIgnore` class

### PR DESCRIPTION
**Pull request by alestiago**
## Status

**READY FOR REVIEW**

## Description

This is a part of https://github.com/felangel/mason/issues/781, yet to be followed by another Pull Request to adjust the bundling logic.

Changes:
- Adds the `glob` dependency
- Adds `BrickIgnore` class
- Defines `BrickIgnore.isIgnored` and `BrickIgnore.fromFile`

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by wolfenrain — APPROVED** [review]

**Comment by felangel** [comment]
I'll have a closer look tomorrow, apologies for the delayed review!

**Comment by felangel** [comment]
As discussed offline @alestiago would you be okay with pushing additional commits for the remainder of the changes so that everything can be reviewed as a whole (I know the diff will be larger) but it would be helpful for me to review everything together to make sure it all integrates well. Sorry for the delay on this and looking forward to getting it merged 🎉

**Comment by felangel** [comment]
Closing this for now since it's been a while but happy to take a look whenever you have time to pick it back up!

**Comment by alestiago** [comment]
Sounds good! I haven't had bandwidth to tackle this, I'll let you know if I have any at some point!

**Pull request closed without merging**
